import Head from "next/head";
import Link from "next/link";
// main container
const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " - BagHive" : "BagHive"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen">
        <header>
          <nav className="flex justify-between items-center shadow-md px-4 h-12">
            <Link href="/" className="text-lg font-bold">
              BagHive
            </Link>
            <div>
              <Link href="/cart" className="p-2">
                Cart
              </Link>
              <Link href="/login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container w-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center shadow-inner h-10">
          Copyright to 2023 BagHive
        </footer>
      </div>
    </>
  );
};

export default Layout;
